module.exports = function () {
  return {
    students: [
      {
        id: 1,
        name: "Alice Johnson",
        age: 14,
        gender: "Female",
        class: "9",
        section: "A",
        subjects: ["Math", "Science", "English"],
        contact: {
          email: "alice.johnson@example.com",
          phone: "123-456-7890",
        },
      },
      {
        id: 2,
        name: "Bob Smith",
        age: 15,
        gender: "Male",
        class: "10",
        section: "B",
        subjects: ["Math", "History", "Geography"],
        contact: {
          email: "bob.smith@example.com",
          phone: "234-567-8901",
        },
      },
      {
        id: 3,
        name: "Charlie Lee",
        age: 13,
        gender: "Non-binary",
        class: "8",
        section: "C",
        subjects: ["Science", "English", "Art"],
        contact: {
          email: "charlie.lee@example.com",
          phone: "345-678-9012",
        },
      },
      {
        id: 4,
        name: "Diana Patel",
        age: 14,
        gender: "Female",
        class: "9",
        section: "A",
        subjects: ["Math", "Biology", "English"],
        contact: {
          email: "diana.patel@example.com",
          phone: "456-789-0123",
        },
      },
      {
        id: 5,
        name: "Ethan Brown",
        age: 15,
        gender: "Male",
        class: "10",
        section: "B",
        subjects: ["Physics", "Chemistry", "Math"],
        contact: {
          email: "ethan.brown@example.com",
          phone: "567-890-1234",
        },
      },
      {
        id: 6,
        name: "Fiona Green",
        age: 13,
        gender: "Female",
        class: "8",
        section: "C",
        subjects: ["English", "History", "Art"],
        contact: {
          email: "fiona.green@example.com",
          phone: "678-901-2345",
        },
      },
      {
        id: 7,
        name: "George White",
        age: 14,
        gender: "Male",
        class: "9",
        section: "A",
        subjects: ["Math", "Science", "Geography"],
        contact: {
          email: "george.white@example.com",
          phone: "789-012-3456",
        },
      },
      {
        id: 8,
        name: "Hannah Black",
        age: 15,
        gender: "Female",
        class: "10",
        section: "B",
        subjects: ["Biology", "English", "History"],
        contact: {
          email: "hannah.black@example.com",
          phone: "890-123-4567",
        },
      },
      {
        id: 9,
        name: "Ian Gray",
        age: 13,
        gender: "Male",
        class: "8",
        section: "C",
        subjects: ["Math", "Science", "Physical Education"],
        contact: {
          email: "ian.gray@example.com",
          phone: "901-234-5678",
        },
      },
      {
        id: 10,
        name: "Jasmine Blue",
        age: 14,
        gender: "Female",
        class: "9",
        section: "A",
        subjects: ["English", "Art", "Geography"],
        contact: {
          email: "jasmine.blue@example.com",
          phone: "012-345-6789",
        },
      },
    ],
  };
};
